name: Publish BOM

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .gradle/
          key: ${{ runner.os }}-kommon-publish

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Prepare version
        id: prepare_version
        run: |
          LATEST_TAG=$(git tag --sort "-committerdate" | cut -d$'\n' -f1 | grep -E '^[0-9]+.[0-9]+.[0-9]+$')
          CURRENT_VERSION="${LATEST_TAG:-0.0.0}"
          IFS='.' read -ra VERSION_SPLIT <<< $CURRENT_VERSION          
          NEW_VERSION=${VERSION_SPLIT[0]}.${VERSION_SPLIT[1]}.$((${VERSION_SPLIT[2]} + 1))
          echo new version: $NEW_VERSION
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -i publishToGithubPackages
          cache-read-only: false
        env:
          PUBLISH_VERSION: ${{ steps.prepare_version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.prepare_version.outputs.version }}
          tag_prefix: ""

      - name: Restore Cache
        uses: actions/cache/save@v3
        if: success()
        with:
          path: |
            .gradle/
          key: ${{ runner.os }}-kommon-publish-${{ github.run_id }}
